import re

def format_product_names(product_names):
    """Formats product names by capitalizing the first two words."""
    formatted_names = []
    
    for name in product_names:
        words = name.split()
        
        if not words:
            formatted_names.append(name)  # Keep empty lines unchanged
            continue
        
        # Capitalize the first two words (if they exist)
        words[0] = words[0].capitalize()
        if len(words) > 1:
            words[1] = words[1].capitalize()
        
        # Join the words back together
        formatted_names.append(" ".join(words))

    return formatted_names

def extract_item_names(sql_insert_statement):
    """Extracts item names from the SQL INSERT statement."""
    # Regular expression to match values inside the insert statement
    matches = re.findall(r"\(\d+, '(.*?)',", sql_insert_statement)
    
    # Format extracted item names
    formatted_names = format_product_names(matches)
    
    # Generate new SQL INSERT statement
    new_sql = "INSERT INTO `items` (`name`) VALUES " + ", ".join(f"('{name}')" for name in formatted_names) + ";"
    
    return new_sql

# Old SQL INSERT statement (paste your actual statement here)
old_sql = """INSERT INTO `item` (`id`, `name`, `item_type`, `image`, `quantity`) VALUES
(4, 'BROOM HEAD (ea)', 1, '/public/images/broomhead.jpg', 0),
(5, 'CENTER PULL TOWELS (ro)', 1, '/public/images/centertowels.jpg', 0),
(6, 'DECK BRUSH 10\" (ea)', 1, '/public/images/deckbrush.jpg', 0),
(7, 'DUST MOP HEAD (ea) ', 1, '/public/images/dustmop.jpg', 0),
(9, 'MOP HEAD f/SEALER (ea) ', 1, '/public/images/mophead.jpg', 0),
(10, 'CLOTH RAG (ea)', 1, '/public/images/clothrag.jpg', 0),
(14, 'SPRAY BOTTLE 1 QT (ea) ', 1, '/public/images/spraybottle.jpg', 0),
(15, 'SPRAY HEAD f/BT (ea) ', 1, '/public/images/sprayhead.jpg', 0),
(16, 'TRASH BAGS SM (ro) ', 1, '/public/images/trashbagsmall.jpg', 0),
(17, 'TRASH BAGS MED (bx) ', 1, '/public/images/trashbagsmall.jpg', 0),
(18, 'TRASH BAGS LG (bx) ', 1, '/public/images/trashbagsmall.jpg', 0),
(19, 'PLASTIC BAGS f/RECYCLING (ro) ', 1, '/public/images/recycle.jpg', 0),
(21, 'BUFF PAD CHAMPAGINE (ea)', 1, '/public/images/buffpadchamp.jpg', 0),
(22, 'POLISHING PAD WHITE (ea) ', 1, '', 0),
(23, 'STRIP PAD BLACK (ea)', 1, '', 0),
(24, 'CLEAN PAD GREEN (ea) ', 1, '/public/images/greenpad.jpg', 0),
(25, 'PAPER TOWELS MFLD (cs) ', 1, '/public/images/brownpapertowels.jpg', 0),
(26, 'TOILET PAPER (cs) ', 1, '/public/images/toiletpaper.jpg', 0),
(27, 'VINYL, GLOVES, PF,MED (bx) ', 1, '/public/images/gloves.png', 0),
(29, 'VINYL, GLOVES, PF, XL (bx) ', 1, '/public/images/gloves.png', 0),
(30, 'GLOVES FOOD HANDLING (pk)', 1, '/public/images/foodhandling.jpg', 0),
(31, 'MELT-A-WAY LAUNDRY BAGS (ro)', 1, '/public/images/meltaway.jpg', 0),
(32, 'GREEN ANTIBACT HAND SOAP (ea)', 1, '/public/images/greenhandsoap.jpg', 0),
(33, 'ANTIBACT FOAM HAND SOAP (ea)', 1, '/public/images/foaminghandsoap.jpg', 0),
(34, 'RAZOR (bx', 9, '/public/images/razor.jpg', 0),
(36, 'SOLAR BRITE (5gl) ', 1, '/public/images/solarbrite.jpg', 0),
(37, 'SANITARY NAPKINS (bx)', 9, '/public/images/sanitary_napkin.jpg', 0),
(38, 'SO FRESH (5gl)', 1, '/public/images/so_fresh.jpg', 0),
(39, 'STAIN BLASTER (pk) ', 1, '/public/images/stainblaster.jpg', 0),
(40, 'GROUT SAFE (gl)', 1, '/public/images/H2 Orange.jpg', 0),
(41, 'GLASS CLEANER (bt) ', 1, '/public/images/glass_cleaner.jpg', 0),
(42, 'NABC1 (bt) ', 1, '/public/images/nabc1.jpg', 0),
(43, 'TRI BASE (gl)', 1, '/public/images/tribase.jpg', 0),
(44, 'PUMP SPRAY (gl)', 1, '/public/images/pump_spray.jpg', 0),
(45, 'SCUM B GONE (bt)', 1, '/public/images/scum_b_gone.jpg', 0),
(46, 'RRJ LEAVE REQUEST FORM (pk)', 2, '/public/images/leave_slip.png', 0),
(47, 'TABLET STANDARD (ea)', 2, '/public/images/tablet_standard.jpg', 0),
(48, 'STENO NOTE BOOK (ea) ', 2, '/public/images/steno.jpg', 0),
(49, 'POST IT LARGE (pk)', 2, '/public/images/post_it.jpg', 0),
(50, 'LOG BOOK 300PG (ea)', 2, '/public/images/logbook.jpg', 0),
(51, 'ENVELOPE COIN (bx)', 2, '/public/images/coinenvelope.jpg', 0),
(52, 'ENVELOPE INTER OFFICE (ea) ', 2, '/public/images/interofficeenevelope.jpg', 0),
(53, 'ENVELOPE WINDOW (bx) ', 2, '/public/images/windowenvelope.jpg', 0),
(54, 'ENVELOPE 9 X 12 (bx)', 2, '/public/images/9x12envelope.jpg', 0),
(55, 'ENVELOPE 10X15 (bx)', 2, '/public/images/10x15envelope.jpg', 0),
(56, 'ENVELOPE STD. WHITE (bx)', 2, '/public/images/envelopes.jpg', 0),
(57, 'CLIP PLASTIC MEDIUM (bx) ', 2, '/public/images/paperclips.jpg', 0),
(58, 'CLIP PLASTIC LARGE (bx) ', 2, '/public/images/paperclips.jpg', 0),
(59, 'CLIP PLASTIC XTRA-LG(bx) ', 2, '/public/images/paperclips.jpg', 0),
(60, 'PEN BLACK (bx)', 2, '/public/images/blackpen.jpg', 0),
(61, 'PEN RED (bx) ', 2, '/public/images/redpen.jpg', 0),
(62, 'PENCILS (pk) ', 2, '/public/images/pencils.jpg', 0),
(63, 'MARKERS BLACK (ea) ', 2, '/public/images/blackmarker.jpg', 0),
(64, 'HIGHLITER YEL (ea) ', 2, '/public/images/highlighter-yellow.jpg', 0),
(65, 'DRY ERASE MKR (PK) ', 2, '/public/images/dryerasemarker.png', 0),
(66, 'DRY ERASER (ea) ', 2, '/public/images/dryeraser.jpg', 0),
(67, 'POCKET PORTFOLIO (ea)', 2, '/public/images/pocket_portfolio.jpg', 0),
(68, 'LASER LABELS 1/3 CUT (pk)', 2, '/public/images/laserlabels.jpg', 0),
(69, 'LASER LABELS MAILING (pk)', 2, '/public/images/laserlabels.jpg', 0),
(70, 'LASER LABELS 1\" X 2 5/8\" (bx)', 2, '/public/images/laserlabels.jpg', 0),
(71, 'FILE FOLDER STD (bx)', 2, '/public/images/file_folder.jpg', 0),
(72, 'BATTERY AA CELL (ea)', 2, '/public/images/AA-battery.jpg', 0),
(73, 'BATTERY AAA CELL (ea)', 2, '/public/images/AAA-battery.jpg', 0),
(74, 'BATTERY C CELL (ea)', 2, '/public/images/c-cellbattery.jpg', 0),
(75, 'BATTERY D CELL (ea)', 2, '/public/images/d-cellbattery.jpg', 0),
(76, 'BATTERY 9 VOLT (ea)', 2, '/public/images/9-volt.jpg', 0),
(77, 'STAPLER (ea) (staple-less)', 2, '/public/images/stapler.jpg', 0),
(78, 'TAPE TRANSPARENT (ro)', 2, '/public/images/tape_roll.jpg', 0),
(79, 'RUBBER BANDS (pk)', 2, '/public/images/rubber_bands.jpg', 0),
(80, 'WHITEOUT PEN (ea)', 2, '/public/images/whiteoutpen.jpg', 0),
(81, 'WHITEOUT (bt)', 2, '/public/images/whiteout.jpg', 0),
(82, 'TNG/CLASS RECORD FOLDER (bx) 13775', 2, '', 0),
(83, 'PERSONNEL RECORD FOLDER (bx)', 2, '/public/images/personnel_folder.jpg', 0),
(84, 'SUPERVISOR RECORD FOLDER (bx)', 2, '/public/images/supervisor_folder.jpg', 0),
(87, 'COPY PAPER 8.5x11 (cs)', 2, '/public/images/paper.jpg', 0),
(88, 'BANKER BOX, LTR, lg (ea)', 2, '/public/images/bankerbox.jpg', 0),
(89, 'BANKER BOX, LEGAL (ea)', 2, '/public/images/bankerbox.jpg', 0),
(90, 'BANKER BOX, LTR, sm (ea)', 2, '/public/images/bankerbox.jpg', 0),
(91, 'Q5949X (ea)', 3, '/public/images/49x', 0),
(92, 'CB436A (ea)', 3, '/public/images/36a.jpg', 0),
(93, 'CE278A (ea)', 3, '/public/images/78a.png', 0),
(94, 'Q7553X (ea)', 3, '/public/images/53x.png', 0),
(95, 'CE505X (ea)', 3, '/public/images/05x.jpg', 0),
(96, '0 C4127X (ea)', 3, '/public/images/0 C4127.jpg', 0),
(97, 'CC364A (ea)', 3, '/public/images/64a.png', 0),
(98, 'C8061X (ea)', 3, '/public/images/61x.png', 0),
(99, '600 (ea)', 3, '/public/images/90a.jpg', 0),
(100, 'D130 (ea)', 3, '', 0),
(101, 'BROTHER 350 (ea)', 3, '/public/images/brother350.jpg', 0),
(102, '98X (ea)', 3, '/public/images/98X.jpg', 0),
(103, 'CF280A (ea)', 3, '/public/images/80a.jpg', 0),
(104, '92A (ea)', 3, '/public/images/92a.jpg', 0),
(105, 'C7115X (ea)', 3, '/public/images/C7115X.jpg', 0),
(106, 'Q2613 (ea)', 3, '/public/images/13a.jpg', 0),
(110, 'Straw Broom (ea)', 1, '/public/images/strawbroom.jpg', 0),
(116, 'SEALER WAY (gl)', 1, '', 0),
(117, 'STRIPPER (gl)', 1, '', 0),
(118, 'BLEACH', 1, '/public/images/bleach.jpg', 0),
(119, 'H2 ORANGE (gl)', 1, '/public/images/H2 Orange.jpg', 0),
(157, 'Green Jumpers Med', 4, '/public/images/greenjumpsuit.jpg', 0),
(158, 'Green Jumpers LG', 4, '/public/images/greenjumpsuit.jpg', 0),
(159, 'Green Jumpers XL', 4, '/public/images/greenjumpsuit.jpg', 0),
(160, 'Green Jumpers 2XL', 4, '/public/images/greenjumpsuit.jpg', 0),
(161, 'Green Jumpers 3XL', 4, '/public/images/greenjumpsuit.jpg', 0),
(162, 'Green Jumpers 4XL', 4, '/public/images/greenjumpsuit.jpg', 0),
(163, 'Green Jumpers 5XL', 4, '/public/images/greenjumpsuit.jpg', 0),
(164, 'Green Jumpers 6XL', 4, '/public/images/greenjumpsuit.jpg', 0),
(165, 'Green Jumpers 7XL', 4, '/public/images/greenjumpsuit.jpg', 0),
(166, 'Green Jumpers 8XL', 4, '/public/images/greenjumpsuit.jpg', 0),
(167, 'Green Jumpers 9XL', 4, '/public/images/greenjumpsuit.jpg', 0),
(168, 'Green Jumpers 10XL', 4, '/public/images/greenjumpsuit.jpg', 0),
(169, 'GYM SHORTS SM', 4, '/public/images/gymshorts.jpg', 0),
(170, 'GYM SHORTS MED', 4, '/public/images/gymshorts.jpg', 0),
(171, 'GYM SHORTS LG', 4, '/public/images/gymshorts.jpg', 0),
(172, 'GYM SHORTS XL', 4, '/public/images/gymshorts.jpg', 0),
(173, 'GYM SHORTS 2XL', 4, '/public/images/gymshorts.jpg', 0),
(174, 'GYM SHORTS 3XL', 4, '/public/images/gymshorts.jpg', 0),
(175, 'GYM SHORTS 4XL', 4, '/public/images/gymshorts.jpg', 0),
(176, 'FEMAL BRIEFS SM/5', 4, '/public/images/womenbriefs.jpg', 0),
(177, 'FEMAL BRIEFS MED/6', 4, '/public/images/womenbriefs.jpg', 0),
(178, 'FEMAL BRIEFS LG/7', 4, '/public/images/womenbriefs.jpg', 0),
(179, 'FEMAL BRIEFS XL/8', 4, '/public/images/womenbriefs.jpg', 0),
(180, 'FEMAL BRIEFS 2XL/9', 4, '/public/images/womenbriefs.jpg', 0),
(181, 'FEMAL BRIEFS 3XL/10', 4, '/public/images/womenbriefs.jpg', 0),
(182, 'FEMAL BRIEFS 4XL/11', 4, '/public/images/womenbriefs.jpg', 0),
(183, 'FEMAL BRIEFS 5XL/12', 4, '/public/images/womenbriefs.jpg', 0),
(184, 'FEMAL BRIEFS 6XL/13', 4, '/public/images/womenbriefs.jpg', 0),
(185, 'FEMAL BRIEFS 7XL/14', 4, '/public/images/womenbriefs.jpg', 0),
(186, 'BRA SIZE 32', 4, '/public/images/bra.jpg', 0),
(187, 'BRA SIZE 34', 4, '/public/images/bra.jpg', 0),
(188, 'BRA SIZE 36', 4, '/public/images/bra.jpg', 0),
(189, 'BRA SIZE 38', 4, '/public/images/bra.jpg', 0),
(190, 'BRA SIZE 40', 4, '/public/images/bra.jpg', 0),
(191, 'BRA SIZE 42', 4, '/public/images/bra.jpg', 0),
(192, 'BRA SIZE 44', 4, '/public/images/bra.jpg', 0),
(193, 'BRA SIZE 46', 4, '/public/images/bra.jpg', 0),
(194, 'MENS BRIEFS SM', 4, '/public/images/mensbriefs.jpg', 0),
(195, 'MENS BRIEFS MED', 4, '/public/images/mensbriefs.jpg', 0),
(196, 'MENS BRIEFS LG', 4, '/public/images/mensbriefs.jpg', 0),
(197, 'MENS BRIEFS XL', 4, '/public/images/mensbriefs.jpg', 0),
(198, 'MENS BRIEFS 2XL', 4, '/public/images/mensbriefs.jpg', 0),
(199, 'MENS BRIEFS 3XL', 4, '/public/images/mensbriefs.jpg', 0),
(200, 'MENS BRIEFS 4XL', 4, '/public/images/mensbriefs.jpg', 0),
(201, 'T-SHIRTS SM', 4, '/public/images/t-shirts.jpg', 0),
(202, 'T-SHIRTS MED', 4, '/public/images/t-shirts.jpg', 0),
(203, 'T-SHIRTS LG', 4, '/public/images/t-shirts.jpg', 0),
(204, 'T-SHIRTS XL', 4, '/public/images/t-shirts.jpg', 0),
(205, 'T-SHIRTS 2XL', 4, '/public/images/t-shirts.jpg', 0),
(206, 'T-SHIRTS 3XL', 4, '/public/images/t-shirts.jpg', 0),
(207, 'T-SHIRTS 4XL', 4, '/public/images/t-shirts.jpg', 0),
(208, 'T-SHIRTS 5XL', 4, '/public/images/t-shirts.jpg', 0),
(209, 'T-SHIRTS 6XL', 4, '/public/images/t-shirts.jpg', 0),
(210, 'T-SHIRTS 7XL', 4, '/public/images/t-shirts.jpg', 0),
(211, 'T-SHIRTS 8XL', 4, '/public/images/t-shirts.jpg', 0),
(212, 'T-SHIRTS 9XL', 4, '/public/images/t-shirts.jpg', 0),
(213, 'T-SHIRTS 10XL', 4, '/public/images/t-shirts.jpg', 0),
(214, 'SHEETS', 4, '/public/images/sheets.jpg', 0),
(215, 'BLANKETS', 4, '/public/images/inmateblankets.jpg', 0),
(216, 'GRAY BLANKETS', 4, '/public/images/blankets.jpg', 0),
(217, 'WASH CLOTHES', 4, '/public/images/clothrag.jpg', 0),
(218, 'TOWELS', 4, '/public/images/towels.jpg', 0),
(219, 'CUPS', 4, '/public/images/cups.webp', 0),
(220, 'SPOONS', 4, '/public/images/spoon.jpg', 0),
(221, 'SHOES SIZE 5', 4, '/public/images/shoes.jpg', 0),
(222, 'SHOES SIZE 6', 4, '/public/images/shoes.jpg', 0),
(223, 'SHOES SIZE 7', 4, '/public/images/shoes.jpg', 0),
(224, 'SHOES SIZE 8', 4, '/public/images/shoes.jpg', 0),
(225, 'SHOES SIZE 9', 4, '/public/images/shoes.jpg', 0),
(226, 'SHOES SIZE 10', 4, '/public/images/shoes.jpg', 0),
(227, 'SHOES SIZE 11', 4, '/public/images/shoes.jpg', 0),
(228, 'SHOES SIZE 12', 4, '/public/images/shoes.jpg', 0),
(229, 'SHOES SIZE 13', 4, '/public/images/shoes.jpg', 0),
(230, 'SHOES SIZE 14', 4, '/public/images/shoes.jpg', 0),
(231, 'SHOES SIZE 15', 4, '/public/images/shoes.jpg', 0),
(232, 'SHOES SIZE 16', 4, '/public/images/shoes.jpg', 0),
(233, 'SHOWER SHOES SM/5&6', 4, '/public/images/showershoes.jpg', 0),
(234, 'SHOWER SHOES MED/7&8', 4, '/public/images/showershoes.jpg', 0),
(235, 'SHOWER SHOES LG/9&10', 4, '/public/images/showershoes.jpg', 0),
(236, 'SHOWER SHOES XL/11&12', 4, '/public/images/showershoes.jpg', 0),
(237, 'SHOWER SHOES 2XL/13&14', 4, '/public/images/showershoes.jpg', 0),
(238, 'SHOWER SHOES 3XL/15&16', 4, '/public/images/showershoes.jpg', 0),
(244, 'Inmate Request Forms', 2, '', 0),
(247, 'Nitrile Gloves', 1, '', 0),
(248, 'Socks', 4, '', 0),
(249, '55a, ink cartridge', 3, '', 0),
(250, 'Broom Handle', 8, '', 0),
(251, '58a ink cartridge', 3, '', 0),
(252, 'Laundry Destainer (bleach)', 1, '', 5),
(253, '83a ink cartridge', 3, '', 0),
(254, 'Laundry Bags', 4, '', 0),
(255, 'Mop Handle', 8, '', 0),
(256, 'Scrub Brush', 8, '', 0),
(257, 'Inmate Bar Soap', 1, '', 0),
(258, 'Dust Pan', 8, '', 0),
(259, 'Toilet Brush', 8, '', 0),
(260, 'Spray Buff (gl)', 1, '', 0),
(261, 'Receipt Book (ea)', 2, '', 0),
(262, 'Personnel File (bx) 14075', 2, '', 0),
(263, 'Supervisor File (bx) 14076', 2, '', 0),
(264, 'Inmate Flex Pen (ea)', 2, '', 0),
(265, 'Mop Bucket (ea)', 1, '', 0),
(266, 'HP148a/ HP148x', 3, '', 0),
(267, 'CE30a', 3, '', 0);"""

# Generate the new insert statement
new_sql = extract_item_names(old_sql)

# Print new SQL statement
print("\nGenerated SQL Query:\n")
print(new_sql)

